language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t benjtlv/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true benjtlv/react-test npm test -- --coverage

after_success:
  - docker build -t benjtlv/multi-client ./client
  - docker build -t benjtlv/multi-nginx ./nginx
  - docker build -t benjtlv/multi-server ./server
  - docker build -t benjtlv/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push benjtlv/multi-client
  - docker push benjtlv/multi-nginx
  - docker push benjtlv/multi-server
  - docker push benjtlv/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  bucket_name: elasticbeanstalk-us-east-1-664889048139
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY